'use server';
import { prisma } from './prisma';
import { requireAuth } from './auth';
import { leadSchema, clientSchema, projectSchema, documentSchema, preAnalysisSchema } from './validation';
import { prepareAiOutput, getAiAdapter } from './ai';
async function audit(actorId: string, event: string, entityType: string, entityId?: string, after?: unknown) { await prisma.auditLog.create({ data: { actorId, event, entityType, entityId, after: after as object } }); }
export async function createLead(form: FormData) { const s = await requireAuth(); const data = leadSchema.parse(Object.fromEntries(form)); const lead = await prisma.lead.create({ data }); await audit(s.userId, 'lead_create', 'Lead', lead.id, lead); return lead; }
export async function createClient(form: FormData) { const s = await requireAuth(); const data = clientSchema.parse(Object.fromEntries(form)); const client = await prisma.client.create({ data: data as never }); await audit(s.userId, 'client_create', 'Client', client.id, client); return client; }
export async function createProject(form: FormData) { const s = await requireAuth(); const data = projectSchema.parse(Object.fromEntries(form)); const project = await prisma.project.create({ data: data as never }); await audit(s.userId, 'project_create', 'Project', project.id, project); return project; }
export async function registerDocument(form: FormData) { const s = await requireAuth(); const data = documentSchema.parse(Object.fromEntries(form)); const document = await prisma.document.create({ data: { ...data, uploadedById: s.userId } }); await audit(s.userId, 'document_upload_metadata', 'Document', document.id, document); return document; }
export async function createPreAnalysis(form: FormData) { const s = await requireAuth(); const data = preAnalysisSchema.parse(Object.fromEntries(form)); const pre = await prisma.preAnalysis.create({ data: data as never }); await audit(s.userId, 'preanalysis_create', 'PreAnalysis', pre.id, pre); return pre; }
export async function runMockAgent(agentCode: string, input: unknown) { const s = await requireAuth(); const agent = await prisma.aiAgent.findUniqueOrThrow({ where: { code: agentCode } }); const draft = await getAiAdapter().run(agentCode, input); const run = await prisma.aiRun.create({ data: { agentId: agent.id, input: input as object, output: draft as object, createdById: s.userId } }); const prepared = prepareAiOutput(draft); const output = await prisma.aiOutput.create({ data: { aiRunId: run.id, title: prepared.title, content: prepared.content, status: prepared.forbiddenPhrases.length ? 'flagged' : 'needs_review', requiresHumanReview: true, forbiddenPhrases: prepared.forbiddenPhrases } }); await audit(s.userId, 'ai_generation', 'AiOutput', output.id, output); return output; }
export async function approveAiOutput(id: string) { const s = await requireAuth(['admin','direzione','revisore']); const output = await prisma.aiOutput.update({ where: { id }, data: { status: 'approved', approvedById: s.userId, approvedAt: new Date(), reviewedById: s.userId, reviewedAt: new Date() } }); await audit(s.userId, 'ai_approval', 'AiOutput', id, output); return output; }
