#!/usr/bin/env bash
# CI build transport regression. Generated bytes only; no Pro plugin or DB.
set -Eeuo pipefail
[[ "${GITHUB_ACTIONS:-}" == true && "${RUNNER_OS:-}" == Linux ]] || exit 64
[[ -z "${VNX03_PRO_PACKAGE:-}" ]] || exit 64
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
cd "$repo_root"
source_commit="$(git rev-parse HEAD)"
source_tree="$(git rev-parse 'HEAD^{tree}')"
[[ "$source_commit" == "$VNX03_EXPECTED_SOURCE_COMMIT" && "$source_tree" == "$VNX03_EXPECTED_SOURCE_TREE" ]] || exit 64
runtime_dir="$(mktemp -d "$RUNNER_TEMP/fai-vnx03.XXXXXX")"
evidence_dir="$RUNNER_TEMP/r05-n14-candidate-evidence"
mkdir -p "$evidence_dir"
export COMPOSE_PROJECT_NAME="fai-vnx03-transport-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}-$$"
image_names=("$COMPOSE_PROJECT_NAME-harness:$source_commit" "$COMPOSE_PROJECT_NAME-crm:$source_commit" "$COMPOSE_PROJECT_NAME-wordpress:$source_commit")
cleanup_owned=false
cleanup() {
  local code=$? clean=true image ids
  trap - EXIT
  set +e
  if [[ "$cleanup_owned" == true ]]; then
    for image in "${image_names[@]}"; do
      ids="$(docker --context "$docker_context" image ls -q --no-trunc "$image")" || { clean=false; continue; }
      if [[ -n "$ids" ]]; then
        [[ "$(docker --context "$docker_context" image inspect "$image" --format '{{index .Config.Labels "com.docker.compose.project"}}')" == "$COMPOSE_PROJECT_NAME" ]] \
          && docker --context "$docker_context" image rm "$image" >/dev/null || clean=false
      fi
      ids="$(docker --context "$docker_context" image ls -q --no-trunc "$image")" || clean=false
      [[ -z "$ids" ]] || clean=false
    done
  fi
  [[ "$clean" == true ]] || code=1
  python3 -I -B -S - "$evidence_dir/pro-build-transport.json" "$code" "$clean" "$source_commit" "$source_tree" <<'PY'
import json,sys
from pathlib import Path
path,code,clean,head,tree=sys.argv[1:]
Path(path).write_text(json.dumps({'protocol':'PRO_BUILD_TRANSPORT_SYNTHETIC_CI','sourceCommit':head,'sourceTree':tree,
 'exitCode':int(code),'ownedImagesAbsent':clean=='true','syntheticBytesOnly':True,'syntheticPayloadBytes':15*1024*1024,
 'commercialPackageUsed':False,'runtimeProQualified':False,'databaseStarted':False,'productionContact':False},indent=2)+'\n')
PY
  [[ "$runtime_dir" == "$RUNNER_TEMP"/fai-vnx03.?????? ]] && rm -rf -- "$runtime_dir"
  exit "$code"
}
trap cleanup EXIT
fail() { printf '%s\n' "$1" >&2; exit 1; }
docker_context="$(docker context show)"
endpoint="$(docker context inspect "$docker_context" --format '{{ (index .Endpoints "docker").Host }}')"
[[ "$endpoint" == unix:///var/run/docker.sock && -z "${DOCKER_HOST:-}" ]] || fail PRO_CI_LOCAL_ENGINE_REQUIRED
export DOCKER_CONTEXT="$docker_context"
export VNX03_PRO_PYTHON="$(command -v python3)"
source "$repo_root/scripts/vnx03/pro-docker-admission.sh"
pro_bind_builder

# Supply only nonsecret fixture values to render the existing Compose model.
python3 -I -B -S - "$repo_root/tests/vnx03/docker-compose.yml" > "$runtime_dir/variable-names" <<'PY'
from pathlib import Path
import re,sys
print('\n'.join(sorted(set(re.findall(r'\$\{(VNX03_[A-Z0-9_]+)',Path(sys.argv[1]).read_text())))))
PY
while IFS= read -r name; do export "$name=synthetic-ci-only"; done < "$runtime_dir/variable-names"
export VNX03_SOURCE_COMMIT="$source_commit" VNX03_SOURCE_TREE="$source_tree"
export VNX03_WPFORMS_EDITION=pro VNX03_WP_PORT=18083 VNX03_CRM_PORT=18084
export VNX03_PRO_PACKAGE="$runtime_dir/synthetic-package.zip"
python3 -I -B -S - "$VNX03_PRO_PACKAGE" <<'PY'
import sys,zipfile
with zipfile.ZipFile(sys.argv[1],'x',compression=zipfile.ZIP_STORED) as z:
    z.writestr('wpforms/synthetic.txt', b'S' * (15 * 1024 * 1024))
PY
WPFORMS_SHA256="$(sha256sum "$VNX03_PRO_PACKAGE" | cut -d' ' -f1)"
WORDPRESS_IMAGE='wordpress:7.1.3-php8.4-apache@sha256:c74a0947d65b4cf20071d4324e2ac6a80db015451934716ad61f93fe471122ce'
WP_CLI_SHA256=ce34ddd838f7351d6759068d09793f26755463b4a4610a5a5c0a97b68220d85c
mkdir "$runtime_dir/connector"
node tools/package-vnx02-wordpress-connector.mjs --output "$runtime_dir/connector" >/dev/null
VNX03_CONNECTOR_SHA256="$(sha256sum "$runtime_dir/connector/fai-secure-lead-connector-1.2.1.zip" | cut -d' ' -f1)"
export VNX03_WPFORMS_SHA256="$WPFORMS_SHA256" VNX03_WORDPRESS_IMAGE="$WORDPRESS_IMAGE"
export VNX03_WP_CLI_SHA256="$WP_CLI_SHA256" VNX03_CONNECTOR_SHA256
pro_stage_build_input
compose=(docker compose --project-directory "$repo_root" -p "$COMPOSE_PROJECT_NAME" -f tests/vnx03/docker-compose.yml -f tests/vnx03/docker-compose.pro.yml)
pro_require_resource_names_absent
for image in "${image_names[@]}"; do
  ids="$(docker image ls -q --no-trunc "$image")" || fail PRO_CI_IMAGE_INVENTORY_FAILED
  [[ -z "$ids" ]] || fail PRO_CI_IMAGE_COLLISION
done
cleanup_owned=true
pro_build_images
printf 'PRO_SYNTHETIC_LARGE_PACKAGE_BUILD_PASS\n'
