import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';
const app = 'http://127.0.0.1:3000'; const password = process.env.CATALOG_BROWSER_PASSWORD!; const evidence = process.env.CATALOG_BROWSER_EVIDENCE_DIR!;
async function login(page: import('@playwright/test').Page, email: string) { await page.goto(`${app}/login`); await page.locator('[data-interactive-ready="true"]').waitFor({ state: 'attached' }); await page.getByLabel('Email').fill(email); await page.getByLabel('Password').fill(password); await page.getByRole('button', { name: 'Login interno' }).click(); await expect(page).toHaveURL(`${app}/dashboard`); }
test('current and historical catalog remain readable and selectable', async ({ browser }) => {
  mkdirSync(evidence, { recursive: true }); const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } }); const page = await context.newPage(); await login(page, 'catalog-viewer@invalid.test'); await page.goto(`${app}/service-catalog`);
  await expect(page.getByRole('heading', { name: 'Catalogo servizi' })).toBeVisible();
  const optimization = page.getByRole('heading', { name: 'Ottimizzazione Aziendale AI' }).locator('xpath=ancestor::section[1]'); await expect(optimization.getByText('Su preventivo', { exact: true })).toBeVisible(); await expect(optimization.getByText('Versione 1 · € 1.490 + IVA · storica', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Consulenza fiscale', exact: true })).toBeVisible(); await expect(page.getByRole('heading', { name: 'Pianificazione e ottimizzazione fiscale' })).toBeVisible(); await expect(page.getByText('senza garanzia di risparmio fiscale', { exact: false })).toBeVisible(); await expect(page.getByText('La prestazione fiscale è attribuita al professionista abilitato individuato nell’incarico; FAI cura inquadramento e coordinamento.')).toHaveCount(2);
  const fiscalAdvice = page.getByRole('heading', { name: 'Consulenza fiscale', exact: true }).locator('xpath=ancestor::section[1]'); await expect(fiscalAdvice.getByText('la richiesta non accetta una scadenza', { exact: false })).toBeVisible(); await expect(fiscalAdvice.getByRole('heading', { name: 'Deliverable' })).toBeVisible(); await expect(fiscalAdvice.getByRole('heading', { name: 'Incarichi successivi' })).toBeVisible();
  const digitalTypes = page.getByRole('heading', { name: 'Tipologie disponibili' }).locator('xpath=following-sibling::ul[1]'); await expect(digitalTypes.getByRole('listitem')).toHaveCount(7);
  await page.locator('select[name="serviceCode"]').selectOption('progetti_digitali'); await page.locator('select[name="digitalProjectType"]').selectOption('software_crm_workflow'); await page.getByRole('button', { name: 'Consulta selezione' }).click(); const selection = page.getByRole('heading', { name: 'Selezione valida' }).locator('xpath=ancestor::section[1]'); await expect(selection.getByText('Software, CRM e workflow', { exact: true })).toBeVisible();
  await page.screenshot({ path: join(evidence, 'catalog-desktop.png'), fullPage: true }); await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: join(evidence, 'catalog-mobile.png'), fullPage: true });
  const deniedContext = await browser.newContext(); const denied = await deniedContext.newPage(); await login(denied, 'catalog-denied@invalid.test'); await denied.goto(`${app}/service-catalog`); await expect(denied).toHaveURL(`${app}/dashboard`);
  writeFileSync(join(evidence, 'catalog-receipt.json'), JSON.stringify({ synthetic: true, currentRevision: true, historicalRevision: true, quoteOnly: true, fiscalDistinct: true, digitalTypes: 7, selectionValidated: true, unauthorizedDenied: true, desktopScreenshot: true, mobileScreenshot: true }), { mode: 0o600 }); await context.close(); await deniedContext.close();
});
