export const dynamic = 'force-dynamic';

import { Badge, Card, EmptyState, PageHeader, StatusBadge, Table } from '@/components/ui';
import { prisma } from '@/lib/prisma';
import { PrimaryButton, SecondaryLink } from '@/components/actions';
import { assignServiceAndRefresh, updateServiceStatusAndRefresh } from '@/lib/form-actions';

const serviceSections = ['Overview','Anagrafica completa','Azienda / Visura / ATECO','Titolari, soci e amministratori','Progetti','Servizi acquistati','Finanziamento aziendale','Bandi / Finanza agevolata','Bancabilità','Documenti','Pre-analisi','Dossier','Contratti','Pagamenti','Task / Scadenze','Output AI','Audit log'];
const grantFormat = ['Stato misura:','Apertura:','Chiusura:','Risultato atteso:','Difficoltà:','Condizioni bloccanti:','Documenti richiesti:','Prossime azioni:'];
const checklist = ['Documento identità e codice fiscale','Visura camerale / assetto societario','Bilanci o dichiarazioni fiscali','Estratti conto / Centrale Rischi se disponibili','Preventivi e piano investimenti','Contratto o incarico collegato'];

export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const [client, companies, projects, clientServices, documents, contracts, payments, tasks, preAnalyses, dossiers, bankability, financing] = await Promise.all([
    prisma.client.findUnique({ where: { id } }),
    prisma.company.findMany({ where: { clientId: id, deletedAt: null } }),
    prisma.project.findMany({ where: { clientId: id, deletedAt: null } }),
    prisma.clientService.findMany({ where: { clientId: id, deletedAt: null }, orderBy: { createdAt: 'desc' } }),
    prisma.document.findMany({ where: { clientId: id, deletedAt: null }, orderBy: { createdAt: 'desc' } }),
    prisma.contract.findMany({ where: { clientId: id } }),
    prisma.payment.findMany({ where: { clientId: id } }),
    prisma.task.findMany({ where: { clientId: id } }),
    prisma.preAnalysis.findMany({ where: { clientId: id } }),
    prisma.dossier.findMany({ where: { clientId: id } }),
    prisma.bankabilityAssessment.findMany({ where: { clientId: id } }),
    prisma.corporateFinancingAssessment.findMany({ where: { clientId: id } }),
  ]);
  const serviceIds = clientServices.map((service) => service.id);
  const [aiOutputs, auditLogs] = await Promise.all([
    serviceIds.length > 0 ? prisma.aiOutput.findMany({ where: { clientServiceId: { in: serviceIds } }, orderBy: { createdAt: 'desc' } }) : Promise.resolve([]),
    prisma.auditLog.findMany({ where: { OR: [{ entityId: id }, { entityId: { in: serviceIds } }] }, orderBy: { createdAt: 'desc' }, take: 25 }),
  ]);
  if (!client) return <h1 className="text-3xl font-bold text-fai-navy">Cliente non trovato</h1>;
  const catalog = await prisma.serviceCatalog.findMany({ where: { id: { in: clientServices.map((s) => s.serviceCatalogId) } } });
  const users = await prisma.user.findMany({ where: { active: true } });
  const nameOf = (serviceId: string) => catalog.find((s) => s.id === serviceId)?.name ?? 'Servizio FAI';
  const userOf = (userId?: string | null) => users.find((u) => u.id === userId)?.name ?? 'Da assegnare';

  return <div className="space-y-6">
    <PageHeader title={`Fascicolo Cliente Interno — ${client.displayName}`} description="Scheda operativa interna FAI: servizi acquistati, documenti per sezione, output AI in bozza con revisione umana obbligatoria e audit."/><SecondaryLink href="/clients">← Torna alla lista</SecondaryLink>
    <nav className="sticky top-20 z-10 flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-sm backdrop-blur">{serviceSections.map((s) => <a className="rounded-full bg-fai-blue/10 px-3 py-1.5 text-xs font-bold text-fai-blue hover:bg-fai-blue hover:text-white" href={`#${s.toLowerCase().replaceAll(' ', '-').replaceAll('/', '').replaceAll('—', '-')}`} key={s}>{s}</a>)}</nav>
    <div className="grid gap-4 md:grid-cols-4"><Card title="Anagrafica"><p className="font-semibold">{client.displayName}</p><p className="text-sm text-fai-gray">Tipo: {client.type}</p><p className="text-sm text-fai-gray">Stato: {client.status}</p></Card><Card title="Aziende"><p className="text-3xl font-bold text-fai-blue">{companies.length}</p></Card><Card title="Progetti"><p className="text-3xl font-bold text-fai-blue">{projects.length}</p></Card><Card title="Servizi acquistati"><p className="text-3xl font-bold text-fai-blue">{clientServices.length}</p></Card></div>
    <Card title="Servizi acquistati"><div className="grid gap-4 md:grid-cols-2">{clientServices.map((s) => <article id={`service-${s.id}`} key={s.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-fai-navy">{nameOf(s.serviceCatalogId)}</h3><p className="text-sm text-fai-gray">Responsabile: {userOf(s.assignedToId)}</p></div><div className="flex gap-2"><StatusBadge status={s.paymentStatus} /><StatusBadge status={s.status} /></div></div><p className="mt-3 text-sm">Note interne: {s.internalNotes ?? '—'}</p><div className="mt-3 grid gap-2 md:grid-cols-2"><form action={updateServiceStatusAndRefresh} className="flex gap-2"><input type="hidden" name="id" value={s.id}/><select name="status" defaultValue={s.status} className="min-w-0 flex-1 rounded-lg border px-2 py-1">{['richiesto','pagato','raccolta_documenti','in_lavorazione','bozza_ai','revisione_umana','consegnabile','consegnato','sospeso','chiuso','archiviato'].map(st=><option key={st} value={st}>{st}</option>)}</select><PrimaryButton type="submit">Salva</PrimaryButton></form><form action={assignServiceAndRefresh} className="flex gap-2"><input type="hidden" name="id" value={s.id}/><select name="assignedToId" defaultValue={s.assignedToId??''} className="min-w-0 flex-1 rounded-lg border px-2 py-1"><option value="">Da assegnare</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><PrimaryButton type="submit">Assegna</PrimaryButton></form></div><p className="mt-2 text-sm text-fai-gray">Checklist documentale predisposta: {checklist.join(' · ')}</p><h4 className="mt-3 font-semibold">Documenti collegati</h4><ul className="list-disc pl-5 text-sm">{documents.filter((d) => d.clientServiceId === s.id).map((d) => <li key={d.id}>{d.title} — {d.serviceArea} / {d.documentCategory}</li>)}{documents.filter((d) => d.clientServiceId === s.id).length === 0 && <li>Nessun documento collegato a questo servizio</li>}</ul><h4 className="mt-3 font-semibold">Output AI collegati</h4><ul className="list-disc pl-5 text-sm">{aiOutputs.filter((o) => o.clientServiceId === s.id).map((o) => <li key={o.id}>{o.title} — <StatusBadge status={o.status} /> · bozza interna da revisionare</li>)}{aiOutputs.filter((o) => o.clientServiceId === s.id).length === 0 && <li>Nessun output AI da revisionare</li>}</ul><h4 className="mt-3 font-semibold">Task/scadenze</h4><ul className="list-disc pl-5 text-sm">{tasks.filter((t) => t.clientServiceId === s.id).map((t) => <li key={t.id}>{t.title} — {t.status}{t.dueAt ? ` · ${t.dueAt.toISOString().slice(0, 10)}` : ''}</li>)}{tasks.filter((t) => t.clientServiceId === s.id).length === 0 && <li>Nessun task o scadenza collegata</li>}</ul></article>)}</div>{clientServices.length === 0 && <p className="text-sm text-fai-gray">Nessun servizio acquistato ancora registrato.</p>}</Card>
    <Card title="Documenti: Cliente → Servizio acquistato → Sezione">{documents.length === 0 ? <p className="text-sm text-fai-gray">Nessun documento collegato a questo cliente</p> : <Table headers={['Cliente','Servizio acquistato','Sezione di riferimento','Documento','Categoria','Stato']} rows={documents.map((d) => [client.displayName, d.clientServiceId ? nameOf(clientServices.find((service) => service.id === d.clientServiceId)?.serviceCatalogId ?? '') : 'Fascicolo generale cliente', d.serviceArea, d.title, d.documentCategory, d.status])} />}</Card>
    <div className="grid gap-4 lg:grid-cols-2"><Card title="Finanziamento aziendale"><p className="mb-4 text-sm text-fai-gray">Area solo interna: non promette finanziamenti o approvazioni.</p>{financing.length === 0 ? <EmptyState title="Nessuna valutazione finanziamento"/> : <div className="space-y-4">{financing.map((f) => <div key={f.id} className="rounded-xl border border-slate-200 p-4"><div className="grid gap-3 text-sm md:grid-cols-2">{[['Importo richiesto', f.requestedAmount ? `€ ${Number(f.requestedAmount).toLocaleString('it-IT')}` : '—'], ['Finalità', f.purpose ?? '—'], ['Tempi', f.timing ?? '—'], ['Strumenti ordinari', f.ordinaryInstruments ?? '—'], ['Mutuo', f.mortgage ?? '—'], ['Chirografario', f.unsecuredLoan ?? '—'], ['Leasing', f.leasing ?? '—'], ['Factoring', f.factoring ?? '—'], ['Anticipo fatture', f.invoiceAdvance ?? '—'], ['Linee di credito', f.creditLines ?? '—'], ['MCC / garanzie', [f.mcc, f.guarantees].filter(Boolean).join(' · ') || '—'], ['Fabbisogno', f.fundingNeed ?? '—'], ['Rata sostenibile', f.sustainableInstallment ? `€ ${Number(f.sustainableInstallment).toLocaleString('it-IT')}` : '—'], ['DSCR/cashflow', f.dscrCashflow ?? '—'], ['Debiti', f.existingDebts ?? '—'], ['Criticità', f.criticalIssues ?? '—'], ['Scenario A', f.scenarioA ?? '—'], ['Scenario B', f.scenarioB ?? '—'], ['Prossima azione', f.nextAction ?? '—']].map(([k,v]) => <div key={k}><p className="text-xs font-bold uppercase text-fai-gray">{k}</p><p className="font-medium text-fai-navy">{v}</p></div>)}</div></div>)}</div>}</Card><Card title="Bandi / Finanza agevolata"><p className="text-sm text-fai-gray">Formato operativo interno per ogni misura. Le fonti non verificate restano: <strong>Da verificare su fonte ufficiale</strong>.</p><ul className="mt-3 grid gap-2 text-sm">{grantFormat.map((x) => <li className="rounded-lg bg-fai-bg px-3 py-2 font-semibold text-fai-navy" key={x}>{x} <span className="font-normal text-fai-gray">Da compilare/verificare</span></li>)}</ul></Card></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card title="Bancabilità"><p className="text-sm">Assessment: {bankability.length}</p></Card><Card title="Pre-analisi / Dossier"><p className="text-sm">Pre-analisi: {preAnalyses.length} · Dossier: {dossiers.length}</p></Card><Card title="Contratti / Pagamenti"><p className="text-sm">Contratti: {contracts.length} · Pagamenti: {payments.length}</p>{payments.length === 0 && <p className="mt-2 text-sm text-fai-gray">Nessun pagamento registrato</p>}</Card><Card title="Task / Scadenze"><p className="text-sm">Task aperti o storici: {tasks.length}</p></Card></div>
    <Card title="Output AI">{aiOutputs.length === 0 ? <p className="text-sm text-fai-gray">Nessun output AI da revisionare</p> : <Table headers={['Titolo','Stato','Revisione umana','Data']} rows={aiOutputs.map((o) => [o.title, <StatusBadge status={o.status} key='s' />, o.requiresHumanReview ? 'Obbligatoria' : 'Non richiesta', o.createdAt.toISOString()])} />}</Card>
    <Card title="Audit log"><Table headers={['Evento','Entità','Data']} rows={auditLogs.map((a) => [<span className='font-semibold text-fai-navy' key='e'>{a.event}</span>, `${a.entityType ?? ''} ${a.entityId ?? ''}`, a.createdAt.toISOString()])} /></Card>
  </div>;
}
