ALTER TABLE "AiAgent"
  ADD COLUMN "description" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "operationalScope" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "systemPrompt" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "requiredDataChecklist" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN "expectedOutput" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "toneStyle" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "provider" TEXT NOT NULL DEFAULT 'mock',
  ADD COLUMN "futureModel" TEXT,
  ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
