export const dynamic = 'force-dynamic';
import Link from 'next/link';
import { PrimaryButton } from '@/components/actions';
import { Card, EmptyState, PageHeader, StatusBadge } from '@/components/ui';
import { canEditLead, canViewLead } from '@/lib/access-control';
import { hasPermission, requirePermission } from '@/lib/auth';
import { controlledIntakeChannels, controlledSubjectTypes } from '@/lib/controlled-intake';
import { classifyAuthenticated1265, decideControlledDuplicate, recordControlledIntake } from '@/lib/controlled-intake-actions';
import { prisma } from '@/lib/prisma';
import { DIGITAL_PROJECT_TYPES, FAI_SERVICE_CATALOG_V2 } from '@/lib/service-catalog-v2';
import { catalogRevisionIsSelectable } from '@/lib/service-catalog-v2-persistence';
const labels: Record<string, string> = { WPFORMS_1265: 'WPForms 1265 — continuità manuale', WPFORMS_1098: 'WPForms 1098 — brief digitale', WPFORMS_1485: 'WPForms 1485 — richiesta amministrativa', EMAIL: 'Email — registrazione manuale', PERSONA: 'Persona', IMPRESA: 'Impresa', PROFESSIONISTA: 'Professionista', SOGGETTO_DA_COSTITUIRE: 'Soggetto da costituire', ASSOCIAZIONE: 'Associazione', COOPERATIVA: 'Cooperativa', ENTE: 'Ente' };
const field = 'mt-1 w-full rounded-xl border p-3';
export default async function Page({ searchParams }: { searchParams: Promise<{ created?: string }> }) {
  const session = await requirePermission('lead.read'); const params = await searchParams;
  const [records, revisions, automatic1265] = await Promise.all([prisma.controlledIntake.findMany({ include: { duplicateCandidates: true, duplicateDecision: true }, orderBy: { createdAt: 'desc' }, take: 100 }), prisma.serviceCatalogRevision.findMany({ where: { status: 'PUBLISHED' }, include: { serviceCatalog: true } }), prisma.commercialLeadInboxItem.findMany({ where: { originKind: 'BUSINESS_PROJECTION_N13', formCode: '1265', projectionLedgerId: { not: null } }, include: { lead: true }, orderBy: { createdAt: 'desc' }, take: 50 })]);
  const leads = await prisma.lead.findMany({ where: { id: { in: [...new Set(records.flatMap((record) => [record.leadId, ...record.duplicateCandidates.map((candidate) => candidate.leadId)]))] }, deletedAt: null } });
  const leadById = new Map(leads.map((lead) => [lead.id, lead])); const linkedProjectionIds = new Set(records.map(({ sourceProjectionLedgerId }) => sourceProjectionLedgerId).filter(Boolean)); const automaticAvailable = automatic1265.filter((item) => item.projectionLedgerId && !linkedProjectionIds.has(item.projectionLedgerId) && canEditLead(session, item.lead)); const visible = records.filter((record) => { const lead = leadById.get(record.leadId); return lead && canViewLead(session, lead); });
  const enabled = process.env.CONTROLLED_INTAKE_MODE === 'synthetic'; const now = new Date(); const services = FAI_SERVICE_CATALOG_V2.filter((definition) => revisions.some((revision) => revision.serviceCatalog.code === definition.code && catalogRevisionIsSelectable(definition, revision, now)));
  return <div className="space-y-6"><PageHeader title="Acquisizioni controllate" description="Registrazione sintetica: nessun pagamento, firma, accredito, invio o avvio automatico." />
    {params.created && visible.some(({ id }) => id === params.created) ? <p role="status" className="rounded-xl bg-green-50 p-3 font-semibold text-green-800">Richiesta registrata. Lo stato di presa in carico è indicato nella scheda.</p> : null}
    {enabled && hasPermission(session, 'lead.write') && automaticAvailable.length ? <Card title="Classifica ingresso WPForms 1265 autenticato"><div className="space-y-3">{automaticAvailable.map((item) => <form key={item.id} action={classifyAuthenticated1265} className="grid gap-3 md:grid-cols-2"><input type="hidden" name="projectionLedgerId" value={item.projectionLedgerId!} /><p className="md:col-span-2"><strong>Richiesta:</strong> {item.lead.firstName} {item.lead.lastName} · Lead {item.leadId}</p><label>Tipo soggetto<select name="subjectType" className={field}>{controlledSubjectTypes.map((type) => <option key={type} value={type}>{labels[type]}</option>)}</select></label><label>Categoria effettiva<input name="effectiveCategory" className={field} required /></label><label>Esigenza verificata dall’operatore<input name="need" className={field} required /></label><label>Servizio<select name="serviceCode" className={field}><option value="">Da classificare</option>{services.map((service) => <option key={service.code} value={service.code}>{service.name}</option>)}</select></label><label>Tipologia digitale<select name="digitalProjectType" className={field}><option value="">Non applicabile</option>{DIGITAL_PROJECT_TYPES.map((type) => <option key={type.code} value={type.code}>{type.label}</option>)}</select></label><PrimaryButton type="submit">Collega e classifica 1265 autenticato</PrimaryButton></form>)}</div></Card> : null}
    {enabled && hasPermission(session, 'lead.write') ? <Card title="Nuova richiesta"><form action={recordControlledIntake} className="grid gap-3 md:grid-cols-2">
      <label>Canale<select name="channel" className={field} required>{controlledIntakeChannels.map((v) => <option key={v} value={v}>{labels[v]}</option>)}</select></label><label>ID sorgente<input name="sourceId" className={field} required /></label>
      <label>Data sorgente<input name="sourceOccurredAt" type="datetime-local" className={field} required /></label><label>Tipo soggetto<select name="subjectType" className={field}>{controlledSubjectTypes.map((v) => <option key={v} value={v}>{labels[v]}</option>)}</select></label>
      <label>Nome referente<input name="firstName" className={field} required /></label><label>Cognome referente<input name="lastName" className={field} required /></label><label>Nome soggetto, se disponibile<input name="subjectName" className={field} /></label><label>Email<input name="email" type="email" className={field} /></label><label>Telefono<input name="phone" className={field} /></label>
      <label>Servizio verificato<select name="serviceCode" className={field}><option value="">Da classificare</option>{services.map((s) => <option key={s.code} value={s.code}>{s.name} · revisione {s.revisionVersion}</option>)}</select></label><label>Tipologia digitale<select name="digitalProjectType" className={field}><option value="">Non applicabile</option>{DIGITAL_PROJECT_TYPES.map((t) => <option key={t.code} value={t.code}>{t.label}</option>)}</select></label>
      <label>Categoria effettiva<input name="effectiveCategory" className={field} required /></label><label>Budget indicativo<input name="indicativeBudget" type="number" min="0" step="0.01" className={field} /></label><label className="md:col-span-2">Esigenza<textarea name="need" className={field} required /></label><label>Obiettivo<textarea name="objective" className={field} /></label><label>Funzioni<textarea name="functions" className={field} /></label><label>Tempi dichiarati<textarea name="timing" className={field} /></label><label>Materiali dichiarati, non verificati<textarea name="declaredMaterials" className={field} /></label><label>Riferimento dichiarato<input name="engagementReference" className={field} /></label><label>ID preventivo verificabile<input name="commercialOfferId" className={field} /></label><label>ID incarico verificabile<input name="contractId" className={field} /></label><label>Richiesta amministrativa<textarea name="administrativeRequest" className={field} /></label>
      <div className="md:col-span-2"><PrimaryButton type="submit">Registra richiesta</PrimaryButton></div></form></Card> : <EmptyState title={enabled ? 'Consultazione soltanto' : 'Acquisizione non attiva'}>{enabled ? 'Il permesso di scrittura lead è necessario per registrare una richiesta.' : 'Il percorso sintetico è disattivato.'}</EmptyState>}
    <Card title="Richieste accessibili">{visible.length ? <div className="space-y-3">{visible.map((item) => { const lead = leadById.get(item.leadId)!; const candidates = item.duplicateCandidates.filter((candidate) => { const candidateLead = leadById.get(candidate.leadId); return candidateLead && canEditLead(session, candidateLead); }); return <article key={item.id} id={`intake-${item.id}`} className="space-y-2 rounded-xl border p-4"><div className="flex justify-between gap-2"><strong>{item.subjectName || `${item.firstName} ${item.lastName}`}</strong><StatusBadge status={item.status} /></div><p className="text-sm">{labels[item.channel]} · ID {item.sourceId} · {item.acquisitionMode}</p><p><strong>Esigenza:</strong> {item.need}</p>{item.objective ? <p><strong>Obiettivo:</strong> {item.objective}</p> : null}{item.functions ? <p><strong>Funzioni:</strong> {item.functions}</p> : null}<p><strong>Materiali:</strong> {item.declaredMaterials || 'Non dichiarati'}; completezza non verificata.</p><p><strong>Classificazione:</strong> {item.classificationState === 'VERIFIED' ? item.effectiveCategory : 'Da classificare'}{item.digitalProjectType ? ` · ${item.digitalProjectType}` : ''}</p><p><strong>Amministrazione:</strong> {item.administrativeState === 'VERIFIED' ? 'riferimento verificato' : item.administrativeState === 'TO_RECONCILE' ? 'da riconciliare' : 'non applicabile'}{item.declaredEngagementReference ? ` · dichiarato: ${item.declaredEngagementReference}` : ''}</p><p><strong>Assegnazione corrente:</strong> {lead.assignedToId === session.userId ? 'tu' : lead.assignedToId || 'non assegnata'} · <Link className="underline" href={`/leads/${lead.id}`}>Apri lead</Link></p>{hasPermission(session, 'lead.write') && canEditLead(session, lead) && candidates.length && !item.duplicateDecision ? <div><strong>Possibili duplicati accessibili</strong>{candidates.map((candidate) => <form key={candidate.id} action={decideControlledDuplicate} className="mt-2 flex gap-2"><input type="hidden" name="intakeId" value={item.id} /><input type="hidden" name="candidateLeadId" value={candidate.leadId} /><input type="hidden" name="expectedVersion" value={item.version} /><select name="outcome" className={field}><option value="KEEP_DISTINCT">Mantieni distinte</option><option value="LINK_RELATED">Associa come correlate</option></select><PrimaryButton type="submit">Registra decisione</PrimaryButton></form>)}</div> : item.duplicateDecision ? <p>Decisione duplicato: {item.duplicateDecision.outcome}</p> : null}</article>; })}</div> : <EmptyState title="Nessuna acquisizione accessibile" />}</Card></div>;
}
