import { expect, test, type Page } from '@playwright/test';
import { PrismaClient } from '@prisma/client';
import { assertSyntheticCatalogDatabase } from '../../src/lib/service-catalog-v2-persistence';
const db = new PrismaClient();
const app = process.env.PRACTICE_READINESS_BROWSER_ORIGIN!;
test.beforeAll(async () => { expect(new URL(app).hostname).toBe('127.0.0.1'); await assertSyntheticCatalogDatabase(db); });
test.afterAll(() => db.$disconnect());
async function login(page: Page, user: string) {
  await page.goto(app + '/login');
  await page.locator('[data-interactive-ready="true"]').waitFor({ state: 'attached' });
  await page.getByLabel('Email').fill(user + '@invalid.test');
  await page.getByLabel('Password').fill(process.env.PRACTICE_READINESS_BROWSER_PASSWORD!);
  await page.getByRole('button', { name: 'Login interno' }).click();
  await expect(page).toHaveURL(app + '/dashboard');
}
test('packaged internal entry prepares catalog manually and converts a controlled lead', async ({ page, browser }) => {
  const observer = await browser.newContext();
  const read = await observer.newPage();
  await login(read, 'release-observer');
  await read.goto(app + '/service-catalog');
  await expect(read.getByRole('button', { name: 'Prepara catalogo interno' })).toHaveCount(0);
  await observer.close();
  await login(page, 'release-owner');
  await page.goto(app + '/service-catalog');
  await page.getByRole('button', { name: 'Prepara catalogo interno' }).click();
  await expect(page.getByRole('status')).toHaveText('Revisioni interne disponibili.');
  await expect(page.getByRole('button', { name: 'Prepara catalogo interno' })).toHaveCount(0);
  expect(await db.auditLog.count({ where: { actorId: 'release-owner', event: 'service_catalog_v2_prepare' } })).toBe(1);
  await page.goto(app + '/controlled-intakes');
  const form = page.locator('form').filter({ has: page.getByRole('button', { name: 'Registra richiesta', exact: true }) });
  await form.locator('[name="channel"]').selectOption('EMAIL');
  await form.locator('[name="sourceId"]').fill('R05-INTERNAL-MANUAL');
  await form.locator('[name="sourceOccurredAt"]').fill('2026-09-22T12:00');
  await form.locator('[name="subjectType"]').selectOption('PERSONA');
  await form.locator('[name="firstName"]').fill('Soggetto');
  await form.locator('[name="lastName"]').fill('Sintetico R05');
  await form.locator('[name="email"]').fill('r05-manual@invalid.test');
  await form.locator('[name="effectiveCategory"]').fill('consulenza');
  await form.locator('[name="need"]').fill('Collaudo interno con soli dati sintetici');
  await form.getByRole('button', { name: 'Registra richiesta', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Richiesta registrata');
  const intake = await db.controlledIntake.findUniqueOrThrow({ where: { channel_sourceId: { channel: 'EMAIL', sourceId: 'R05-INTERNAL-MANUAL' } } });
  await page.goto(app + '/leads/' + intake.leadId);
  const conversion = page.locator('form').filter({ has: page.getByRole('button', { name: 'Converti in cliente', exact: true }) });
  await conversion.locator('[name="type"]').selectOption('persona_fisica');
  await conversion.getByRole('button', { name: 'Converti in cliente', exact: true }).click();
  await expect.poll(async () => (await db.lead.findUniqueOrThrow({ where: { id: intake.leadId } })).clientId).toBeTruthy();
  expect(await db.internalSession.count()).toBeGreaterThan(0);
});
