import { PrimaryButton, SecondaryLink } from '@/components/actions';
import { Card, EmptyState, PageHeader, StatusBadge, TimestampMeta, formatDateTime } from '@/components/ui';
import { requirePermission } from '@/lib/auth';
import { COMMERCIAL_OFFER_DISCLAIMER } from '@/lib/docx-export';
import { updateCommercialOfferAndRefresh } from '@/lib/form-actions';
import { prisma } from '@/lib/prisma';
import type { CommercialOfferStatus } from '@prisma/client';

const statuses: CommercialOfferStatus[] = ['bozza','inviata','accettata','rifiutata','scaduta'];
const serviceTemplates = [
  ['Verifica AI preliminare FAI', '190'], ['Audit AI Bancabilità FAI', '390'], ['Consulenza Strategica FAI', '500'], ['Pre-Analisi AI Ammissibilità FAI', '890'], ['Dossier Strategico FAI', '890'], ['Ottimizzazione AI Progetto FAI', '890'], ['Business Plan FAI', ''], ['Progetti Digitali / Software / Piattaforme', ''], ['Servizio personalizzato', ''],
];
const label = (value: string) => value.replaceAll('_', ' ');
const money = (value: unknown) => `€ ${Number(value).toLocaleString('it-IT', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
function leadName(lead: { companyName: string | null; firstName: string; lastName: string }) { return lead.companyName || `${lead.firstName} ${lead.lastName}`.trim(); }

export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const session = await requirePermission('lead.read');
  const { id } = await params;
  const offer = await prisma.commercialOffer.findFirst({ where: { id, deletedAt: null } });
  if (!offer) return <PageHeader title="Offerta non trovata" description="Il record richiesto non esiste o non è più disponibile."/>;
  const [lead, client] = await Promise.all([offer.leadId ? prisma.lead.findUnique({ where: { id: offer.leadId } }) : null, offer.clientId ? prisma.client.findUnique({ where: { id: offer.clientId } }) : null]);
  if (lead && !(session.role === 'admin' || session.role === 'direzione') && lead.assignedToId && lead.assignedToId !== session.userId) return <PageHeader title="Offerta non disponibile" description="L’offerta è collegata a un lead assegnato a un altro utente."/>;
  const canWrite = ['admin','direzione','commerciale','consulente'].includes(session.role);
  return <div className="space-y-6"><PageHeader title={`Offerta commerciale — ${offer.title}`} description="Documento commerciale FAI strutturato, collegato a lead e/o cliente, modificabile ed esportabile in Word."/>
    <div className="flex flex-wrap gap-3"><SecondaryLink href={offer.leadId ? `/leads/${offer.leadId}` : '/leads'}>← Torna al lead</SecondaryLink><SecondaryLink href={`/commercial-offers/${offer.id}/export/docx`}>Esporta Word (.docx)</SecondaryLink></div>
    <div className="grid gap-4 md:grid-cols-2"><Card title="Dati offerta"><div className="space-y-2 text-sm leading-7 text-slate-600"><p>Lead: {lead ? leadName(lead) : '—'}</p><p>Cliente: {client?.displayName ?? '—'}</p><p>Stato: <StatusBadge status={offer.status}/></p><p>Imponibile: {money(offer.taxableAmount)}</p><p>IVA 22%: {money(offer.vatAmount)}</p><p>Totale IVA inclusa: {money(offer.totalAmount)}</p><p>Validità: {offer.validUntil ? formatDateTime(offer.validUntil) : 'Da confermare'}</p></div><TimestampMeta createdAt={offer.createdAt} updatedAt={offer.updatedAt}/></Card>
    <Card title="Template servizi FAI"><div className="grid gap-2 text-sm">{serviceTemplates.map(([name, price])=><div key={name} className="rounded-xl border bg-white p-3"><strong>{name}</strong><span className="ml-2 text-slate-500">{price ? `${price} € + IVA` : 'prezzo manuale'}</span></div>)}</div></Card></div>
    <Card title="Documento commerciale strutturato"><div className="space-y-5 text-sm leading-7 text-slate-700"><section><h3 className="font-black text-fai-navy">Intestazione</h3><p>Finanza Agevola Impresa S.r.l.</p></section><section><h3 className="font-black text-fai-navy">Oggetto offerta</h3><p className="whitespace-pre-wrap">{offer.description || offer.title}</p></section><section><h3 className="font-black text-fai-navy">Servizi proposti</h3><p className="whitespace-pre-wrap">{offer.services || 'Nessun servizio dettagliato.'}</p></section><section><h3 className="font-black text-fai-navy">Descrizione attività incluse</h3><p className="whitespace-pre-wrap">{offer.includedActivities || 'Nessuna descrizione dettagliata.'}</p></section><section><h3 className="font-black text-fai-navy">Condizioni operative</h3><p className="whitespace-pre-wrap">{offer.operationalConditions || 'Da confermare.'}</p></section><section><h3 className="font-black text-fai-navy">Proposta commerciale testuale</h3><p className="whitespace-pre-wrap">{offer.commercialProposal || '—'}</p></section><section><h3 className="font-black text-fai-navy">Disclaimer FAI</h3><p>{COMMERCIAL_OFFER_DISCLAIMER}</p></section></div></Card>
    <Card title="Modifica manuale offerta">{canWrite ? <form action={updateCommercialOfferAndRefresh} className="grid gap-3 md:grid-cols-6"><input type="hidden" name="id" value={offer.id}/>{offer.leadId && <input type="hidden" name="leadId" value={offer.leadId}/>} {offer.clientId && <input type="hidden" name="clientId" value={offer.clientId}/>}<input className="rounded-xl border p-3 md:col-span-3" name="title" defaultValue={offer.title} placeholder="Titolo" required/><select className="rounded-xl border p-3" name="status" defaultValue={offer.status}>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select><input className="rounded-xl border p-3" name="validUntil" type="date" defaultValue={offer.validUntil ? offer.validUntil.toISOString().slice(0,10) : ''}/><input className="rounded-xl border p-3" name="taxableAmount" type="number" step="0.01" defaultValue={String(offer.taxableAmount)} required/><input className="rounded-xl border p-3" name="vatAmount" type="number" step="0.01" defaultValue={String(offer.vatAmount)} required/><input className="rounded-xl border p-3" name="totalAmount" type="number" step="0.01" defaultValue={String(offer.totalAmount)} required/><textarea className="rounded-xl border p-3 md:col-span-6" name="description" defaultValue={offer.description ?? ''} placeholder="Oggetto / descrizione offerta"/><textarea className="rounded-xl border p-3 md:col-span-6" name="services" defaultValue={offer.services ?? ''} placeholder="Servizi proposti"/><textarea className="rounded-xl border p-3 md:col-span-6" name="includedActivities" defaultValue={offer.includedActivities ?? ''} placeholder="Attività incluse"/><textarea className="rounded-xl border p-3 md:col-span-6" name="operationalConditions" defaultValue={offer.operationalConditions ?? ''} placeholder="Condizioni operative"/><textarea className="rounded-xl border p-3 md:col-span-6" name="commercialProposal" defaultValue={offer.commercialProposal ?? ''} placeholder="Proposta commerciale testuale"/><textarea className="rounded-xl border p-3 md:col-span-6" name="notes" defaultValue={offer.notes ?? ''} placeholder="Note interne"/><PrimaryButton type="submit">Salva offerta</PrimaryButton></form> : <EmptyState title="Sola lettura">Non hai permessi di modifica sulle offerte commerciali.</EmptyState>}</Card>
  </div>;
}
