import { OpenLink, PrimaryButton, SecondaryLink } from '@/components/actions';
import { Card, EmptyState, PageHeader, StatusBadge, Table, TimestampMeta, formatDateTime } from '@/components/ui';
import { prisma } from '@/lib/prisma';
import { hasPermission, requirePermission } from '@/lib/auth';
import { canEditLead, canViewLead } from '@/lib/access-control';
import { updateLeadCommercialAndRedirect, convertLeadToClientAndRedirect, createCommercialOfferAndRedirect, claimCommercialLeadInbox, recordCommercialLeadFirstResponse, closeCommercialLeadInbox } from '@/lib/form-actions';
import { commercialLeadInboxMode } from '@/lib/commercial-lead-inbox-contract';
import type { LeadPriority, LeadStatus, LeadSource, CommercialOfferStatus } from '@prisma/client';

const statuses: LeadStatus[] = ['nuovo','da_contattare','contattato','qualificato','non_qualificato','proposta_da_preparare','proposta_inviata','in_trattativa','vinto','perso','archiviato'];
const priorities: LeadPriority[] = ['bassa','media','alta','urgente'];
const offerStatuses: CommercialOfferStatus[] = ['bozza','inviata','accettata','rifiutata','scaduta'];
const label = (value: string) => value === 'sito' ? 'Sito web' : value.replaceAll('_', ' ');
const noteValue = (notes: string | null, label: string) => notes?.split('\n').find((row) => row.startsWith(`${label}: `))?.slice(label.length + 2);
const money = (value: unknown) => `€ ${Number(value).toLocaleString('it-IT', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export default async function Page({params}:{params:Promise<{id:string}>}){
  const session = await requirePermission('lead.read');
  const {id}=await params;
  const lead = await prisma.lead.findFirst({where:{id,deletedAt:null}});
  if(!lead || !canViewLead(session, lead)) return <PageHeader title="Lead non trovato" description="Il record richiesto non esiste o non è accessibile."/>;
  const [users, clients, offers, inboxItem] = await Promise.all([
    prisma.user.findMany({where:{active:true}, select:{id:true,name:true,role:true}}),
    prisma.client.findMany({where:{deletedAt:null}, select:{id:true,displayName:true}}),
    prisma.commercialOffer.findMany({where:{leadId:id,deletedAt:null}, orderBy:{updatedAt:'desc'}}),
    prisma.commercialLeadInboxItem.findUnique({where:{leadId:id}, include:{slaCycles:{orderBy:{sequence:'desc'},take:1}}}),
  ]);
  const owner=lead.assignedToId ? users.find((u)=>u.id===lead.assignedToId) : null;
  const client=lead.clientId ? clients.find((c)=>c.id===lead.clientId) : null;
  const canWrite = hasPermission(session, 'lead.write') && canEditLead(session, lead);
  const canConvert = canWrite && hasPermission(session, 'client.write');
  const now = new Date();
  const next7 = new Date(now); next7.setDate(next7.getDate()+7);
  const hasAcceptedOffer = offers.some((offer)=>offer.status === 'accettata');
  const sourcePage = noteValue(lead.notes, 'Pagina origine');
  const requestedService = noteValue(lead.notes, 'Servizio richiesto');
  const inboxCycle = inboxItem?.slaCycles[0];
  const inboxEnabled = commercialLeadInboxMode() === 'enforced';
  return <div className="space-y-6"><PageHeader title={`Lead — ${lead.companyName || `${lead.firstName} ${lead.lastName}`}`} description="Scheda commerciale con stato vendita, assegnazione, prossima azione, note, offerte e collegamento al cliente."/><SecondaryLink href="/leads">← Torna alla lista</SecondaryLink>
    <div className="grid gap-4 md:grid-cols-2"><Card title="Dati lead"><div className="space-y-2 text-sm leading-7 text-slate-600"><p className="text-lg font-semibold text-fai-navy">{lead.companyName || `${lead.firstName} ${lead.lastName}`}</p><p>Referente: {lead.contactPerson || `${lead.firstName} ${lead.lastName}`}</p><p>Email: {lead.email??'—'} · Telefono: {lead.phone??'—'}</p><p>Provincia/Città: {[lead.province, lead.city].filter(Boolean).join(' / ') || '—'}</p><p>Fonte: <StatusBadge status={label(((lead.leadSource as LeadSource) ?? lead.source) || 'non definito')}/></p><p>Priorità: <StatusBadge status={lead.priority}/></p><p>Interesse: {lead.interest??'—'}</p>{sourcePage && <p>Pagina origine sito: {sourcePage}</p>}{requestedService && <p>Servizio richiesto dal sito: {requestedService}</p>}<p>Importo richiesto/stimato: {lead.requestedAmount ? `€ ${Number(lead.requestedAmount).toLocaleString('it-IT')}` : '—'}</p><p>Budget disponibile: {lead.availableBudget ? `€ ${Number(lead.availableBudget).toLocaleString('it-IT')}` : '—'}</p><p>Stato: <StatusBadge status={lead.status}/></p><p>Consulente assegnato: {owner?.name ?? 'Da assegnare'}</p><p>Cliente collegato: {client ? client.displayName : '—'}</p></div><TimestampMeta createdAt={lead.createdAt} updatedAt={lead.updatedAt} updatedBy={owner?.name ?? lead.assignedToId} /></Card>
    <Card title="Aggiorna pipeline commerciale">{canWrite ? <form action={updateLeadCommercialAndRedirect} className="space-y-3"><input type="hidden" name="id" value={lead.id}/>{inboxItem && ['cliente_acquisito','vinto','perso','archiviato'].includes(lead.status) ? <div className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm">Stato terminale gestito dalla Commercial Lead Inbox: {label(lead.status)}<input type="hidden" name="status" value={lead.status}/></div> : <select name="status" defaultValue={lead.status} className="w-full rounded-xl border p-3">{(inboxItem ? statuses.filter((status) => !['vinto','perso','archiviato'].includes(status)) : statuses).map(s=><option key={s} value={s}>{label(s)}</option>)}</select>}<select name="priority" defaultValue={lead.priority} className="w-full rounded-xl border p-3">{priorities.map(p=><option key={p} value={p}>{label(p)}</option>)}</select>{inboxItem ? <div className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm">Owner gestito dalla Commercial Lead Inbox: {owner?.name ?? 'Da assegnare'}{lead.assignedToId && <input type="hidden" name="assignedToId" value={lead.assignedToId}/>}</div> : <select name="assignedToId" defaultValue={lead.assignedToId ?? ''} className="w-full rounded-xl border p-3"><option value="">Da assegnare</option>{users.map((u)=><option key={u.id} value={u.id}>{u.name}</option>)}</select>}<input className="w-full rounded-xl border p-3" name="nextActionNote" defaultValue={lead.nextActionNote ?? ''} placeholder="Prossima azione"/><input className="w-full rounded-xl border p-3" name="nextActionDate" type="datetime-local" defaultValue={lead.nextActionDate ? lead.nextActionDate.toISOString().slice(0,16) : ''}/><textarea className="w-full rounded-xl border p-3" name="commercialProposal" defaultValue={lead.commercialProposal ?? ''} placeholder="Proposta commerciale / sintesi offerta"/><textarea className="w-full rounded-xl border p-3" name="notes" defaultValue={lead.notes ?? ''} placeholder="Note commerciali"/><PrimaryButton type="submit">Salva aggiornamenti</PrimaryButton></form> : <EmptyState title="Sola lettura">Non hai permessi di scrittura sui lead.</EmptyState>}</Card></div>
    {inboxEnabled && <Card title="Commercial Lead Inbox">{!inboxItem ? <EmptyState title="Lead non iscritto">Nessuna attribution N14 verificata. L’iscrizione manuale nasce soltanto con la creazione atomica del Lead.</EmptyState> : <div className="space-y-3 text-sm text-slate-600"><p>Origine: <StatusBadge status={inboxItem.originKind}/> · Stato: <StatusBadge status={inboxItem.state}/> · Versione {inboxItem.version}</p><p>SLA disponibile {formatDateTime(inboxCycle?.availableAt)} · scadenza {formatDateTime(inboxCycle?.dueAt)} · prima risposta {formatDateTime(inboxCycle?.firstResponseAt)}</p><div className="flex flex-wrap gap-2">{inboxItem.state === 'OPEN' && !lead.assignedToId && hasPermission(session,'lead.inbox.claim') && <form action={claimCommercialLeadInbox}><input type="hidden" name="id" value={lead.id}/><input type="hidden" name="expectedInboxVersion" value={inboxItem.version}/><PrimaryButton type="submit">Prendi in carico</PrimaryButton></form>}{inboxItem.state === 'OPEN' && lead.assignedToId === session.userId && canWrite && !inboxCycle?.firstResponseAt && <form action={recordCommercialLeadFirstResponse}><input type="hidden" name="id" value={lead.id}/><input type="hidden" name="expectedInboxVersion" value={inboxItem.version}/><PrimaryButton type="submit">Registra prima risposta</PrimaryButton></form>}{inboxItem.state === 'OPEN' && lead.assignedToId === session.userId && canWrite && <form action={closeCommercialLeadInbox} className="flex gap-2"><input type="hidden" name="id" value={lead.id}/><input type="hidden" name="expectedInboxVersion" value={inboxItem.version}/><select name="reasonCode" defaultValue="QUALIFIED_OUT" className="rounded-xl border p-2"><option value="QUALIFIED_OUT">Non qualificato</option><option value="LOST">Perso</option><option value="ARCHIVED">Archiviato</option></select><PrimaryButton type="submit">Chiudi</PrimaryButton></form>}</div></div>}</Card>}
    <Card title="Conversione in cliente">{lead.clientId ? <p className="text-sm text-slate-600">Lead già collegato al cliente: <strong>{client?.displayName ?? lead.clientId}</strong>.</p> : canConvert && (!inboxItem || (inboxItem.state === 'OPEN' && lead.assignedToId === session.userId && inboxCycle?.firstResponseAt)) ? <div className="space-y-3">{hasAcceptedOffer ? <p className="rounded-2xl bg-fai-lime/15 p-3 text-sm font-bold text-fai-green ring-1 ring-fai-lime/30">È presente un’offerta accettata: puoi convertire il lead in cliente.</p> : null}<form action={convertLeadToClientAndRedirect} className="flex flex-wrap gap-3"><input type="hidden" name="id" value={lead.id}/>{inboxItem && <input type="hidden" name="expectedInboxVersion" value={inboxItem.version}/>}<select name="type" defaultValue="societa" className="rounded-xl border p-3"><option value="societa">Società</option><option value="ditta_individuale">Ditta individuale</option><option value="persona_fisica">Persona fisica</option><option value="professionista">Professionista</option><option value="soggetto_da_costituire">Soggetto da costituire</option><option value="associazione">Associazione</option><option value="altro">Altro</option></select><PrimaryButton type="submit">Converti in cliente</PrimaryButton></form></div> : <EmptyState title={inboxItem ? "Registra la prima risposta come owner prima della conversione N14" : "Conversione non autorizzata"} />}</Card>
    <Card title="Offerte commerciali">{canWrite ? <form action={createCommercialOfferAndRedirect} className="mb-5 grid gap-3 md:grid-cols-6"><input type="hidden" name="leadId" value={lead.id}/>{lead.clientId && <input type="hidden" name="clientId" value={lead.clientId}/>}<input className="rounded-xl border p-3 md:col-span-2" name="title" placeholder="Titolo offerta" required/><textarea className="rounded-xl border p-3 md:col-span-6" name="services" placeholder="Servizi FAI proposti (puoi copiare dai template nella pagina offerta)"/><input className="rounded-xl border p-3" name="taxableAmount" type="number" step="0.01" placeholder="Imponibile" required/><input className="rounded-xl border p-3" name="vatAmount" type="number" step="0.01" placeholder="IVA" required/><input className="rounded-xl border p-3" name="totalAmount" type="number" step="0.01" placeholder="Totale" required/><select className="rounded-xl border p-3" name="status" defaultValue="bozza">{offerStatuses.map((s)=><option key={s} value={s}>{label(s)}</option>)}</select><textarea className="rounded-xl border p-3 md:col-span-6" name="notes" placeholder="Note offerta"/><PrimaryButton type="submit">Crea offerta</PrimaryButton></form> : null}{offers.length === 0 ? <EmptyState title="Nessuna offerta">Non risultano offerte collegate.</EmptyState> : <Table headers={['Titolo','Totale','Stato','Inviata il','Prossimo follow-up','Azione']} rows={offers.map((o)=>{ const overdue = o.followUpAt && o.followUpAt < now && !['accettata','rifiutata'].includes(o.status); const dueSoon = o.followUpAt && o.followUpAt >= now && o.followUpAt <= next7 && !['accettata','rifiutata'].includes(o.status); return [o.title, money(o.totalAmount), <StatusBadge key="s" status={o.status}/>, o.sentAt ? formatDateTime(o.sentAt) : '—', <span key="f" className={overdue ? 'font-black text-red-600' : dueSoon ? 'font-black text-fai-orange' : ''}>{o.followUpAt ? formatDateTime(o.followUpAt) : '—'}{overdue ? ' · scaduto' : dueSoon ? ' · entro 7 giorni' : ''}</span>, <OpenLink key="o" href={`/commercial-offers/${o.id}`}>Apri offerta</OpenLink>]; })}/>}</Card>
    <Card title="Note interne"><p className="whitespace-pre-wrap text-sm text-fai-gray">{lead.notes??'Nessun dato presente'}</p></Card>
  </div>;
}
