import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { test, expect } from '@playwright/test';
import { PrismaClient } from '@prisma/client';
import { assertAiOrchestratorEphemeralDatabaseIdentity } from '../db/ai-orchestrator-db-test-guard';
const db = new PrismaClient(), root = process.env.CONTRACT_SIGNATURE_EVIDENCE!, password = process.env.CONTRACT_SIGNATURE_BROWSER_PASSWORD!;
const f = JSON.parse(readFileSync(join(root, 'fixture.json'), 'utf8'));
test.afterAll(async () => { await db.$disconnect(); });
test.afterEach(async ({ page }, info) => {
  if (info.status !== info.expectedStatus) console.log('Synthetic CRM page at failure:', await page.locator('body').innerText());
});
test('existing signed document is linked explicitly while payment stays pending', async ({ page }) => {
  await assertAiOrchestratorEphemeralDatabaseIdentity(db); expect(process.env.CONTRACT_SIGNATURE_DB_CONFIRMED).toBe('1'); expect(f.synthetic).toBe(true);
  await page.goto('/login'); await page.locator('[data-interactive-ready="true"]').waitFor({ state: 'attached' });
  await page.getByLabel('Email', { exact: true }).fill('signature-admin@example.test');
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Login interno' }).click(); await expect(page).toHaveURL(/\/dashboard$/);
  await page.goto(`/contracts/${f.contractId}`);
  await expect(page.getByRole('link', { name: 'Apri documenti del cliente' })).toBeVisible();
  await page.getByRole('link', { name: 'Apri documenti del cliente' }).click();
  const upload = page.locator('#documenti form');
  await upload.locator('input[name="file"]').setInputFiles({ name: 'synthetic-signed.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF\n') });
  await upload.locator('input[name="title"]').fill('Synthetic signed contract');
  await upload.locator('select[name="serviceArea"]').selectOption('contratti');
  await upload.locator('input[name="documentCategory"]').fill('contratti');
  await upload.locator('input[name="containsSensitiveData"]').check();
  await upload.getByRole('button', { name: 'Carica', exact: true }).click();
  // The document cell contains both its title and nested file-name text.
  const uploadedRow = page.locator('#documenti table').getByRole('row').filter({ hasText: 'Synthetic signed contract' });
  await expect(uploadedRow).toHaveCount(1);
  await expect(uploadedRow.getByRole('link', { name: 'Scarica', exact: true })).toBeVisible();
  await page.goto(`/contracts/${f.contractId}`);
  const document = await db.document.findFirstOrThrow({ where: { clientId: f.clientId, title: 'Synthetic signed contract' } });
  const version = await db.documentVersion.findFirstOrThrow({ where: { documentId: document.id } });
  await page.getByLabel('Documento firmato *', { exact: true }).selectOption(version.id);
  await page.getByLabel('Data della firma *', { exact: true }).fill('2026-01-01');
  await page.getByRole('checkbox').check();
  await page.screenshot({ path: join(root, 'signature-before.png'), fullPage: true });
  await page.getByRole('button', { name: 'Registra firma già acquisita', exact: true }).click();
  await expect(page.getByText('La firma è registrata. Il pagamento si verifica separatamente nella sezione Pagamenti.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Registra firma già acquisita', exact: true })).toHaveCount(0);
  const saved = await db.contract.findUniqueOrThrow({ where: { id: f.contractId } });
  expect(saved.status).toBe('firmato'); expect(saved.signedDocumentId).toBe(document.id);
  expect((await db.payment.findUniqueOrThrow({ where: { id: f.paymentId } })).status).toBe('da_incassare');
  expect(await db.auditLog.count({ where: { entityId: f.contractId, event: 'contract_signature_recorded' } })).toBe(1);
  expect(await db.practiceReadiness.count({ where: { clientId: f.clientId } })).toBe(0);
  await page.screenshot({ path: join(root, 'signature-after.png'), fullPage: true });
  writeFileSync(join(root, 'browser-proof.json'), JSON.stringify({ synthetic: true, realDocumentUpload: true, signatureLinked: true, paymentStillPending: true, oneAudit: true, noPracticeStarted: true }));
});
