import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { test, expect, type Page } from '@playwright/test';
import { PrismaClient } from '@prisma/client';
import { assertAiOrchestratorEphemeralDatabaseIdentity } from '../db/ai-orchestrator-db-test-guard';
const db = new PrismaClient(), root = process.env.RECORD_PROFILES_EVIDENCE!, password = process.env.RECORD_PROFILES_BROWSER_PASSWORD!;
const f = JSON.parse(readFileSync(join(root, 'fixture.json'), 'utf8'));
async function login(page: Page, role: 'admin' | 'owner' | 'outsider') {
  await page.goto('/login'); await page.locator('[data-interactive-ready="true"]').waitFor({ state: 'attached' });
  await page.getByLabel('Email', { exact: true }).fill(`profiles-${role}@example.test`);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Login interno' }).click(); await expect(page).toHaveURL(/\/dashboard$/);
}
test.afterAll(async () => { await db.$disconnect(); });
test('anagrafica journey persists lead, client, company and referent; outsider and revoked open form cannot write', async ({ browser }) => {
  await assertAiOrchestratorEphemeralDatabaseIdentity(db); expect(process.env.RECORD_PROFILES_BROWSER_CONFIRMED).toBe('1'); expect(f.synthetic).toBe(true);
  const options = { baseURL: 'http://127.0.0.1:3038' };
  const ac = await browser.newContext(options), oc = await browser.newContext(options), xc = await browser.newContext(options);
  const admin = await ac.newPage(), owner = await oc.newPage(), outsider = await xc.newPage();
  await login(admin, 'admin');
  await admin.goto(`/leads/${f.leadId}`); await admin.getByRole('link', { name: 'Modifica anagrafica', exact: true }).click();
  await admin.locator('input[name="phone"]').fill('SYNTHETIC-CONTACT');
  await admin.getByRole('button', { name: 'Salva anagrafica', exact: true }).click(); await expect(admin).toHaveURL(new RegExp(`/leads/${f.leadId}$`));
  expect((await db.lead.findUniqueOrThrow({ where: { id: f.leadId } })).phone).toBe('SYNTHETIC-CONTACT');
  await admin.goto(`/clients/${f.clientId}`); await admin.getByRole('link', { name: 'Modifica anagrafica', exact: true }).click();
  await admin.locator('input[name="displayName"]').fill('Profiles Browser Updated Client');
  await admin.getByRole('button', { name: 'Salva anagrafica', exact: true }).click(); await expect(admin).toHaveURL(/#anagrafica-completa$/);
  await admin.getByRole('link', { name: 'Aggiungi azienda', exact: true }).click();
  await admin.locator('input[name="name"]').fill('Profiles Browser Company');
  await admin.locator('input[name="pec"]').fill('synthetic-company@example.test');
  await admin.locator('input[name="legalAddress"]').fill('Synthetic legal address');
  await admin.locator('input[name="incorporationDate"]').fill('2024-02-29');
  await admin.locator('input[name="employees"]').fill('0');
  await admin.locator('input[name="annualRevenue"]').fill('1234.50');
  await admin.getByRole('button', { name: 'Crea azienda', exact: true }).click(); await expect(admin).toHaveURL(/\/companies\/[a-f0-9-]+$/);
  const company = await db.company.findFirstOrThrow({ where: { clientId: f.clientId, name: 'Profiles Browser Company' } });
  expect(company.annualRevenue?.toString()).toBe('1234.5'); expect(company.employees).toBe(0);
  await admin.getByRole('link', { name: 'Modifica azienda', exact: true }).click();
  await expect(admin.locator('input[name="legalAddress"]')).toHaveValue('Synthetic legal address');
  await admin.locator('input[name="pec"]').fill('');
  await admin.screenshot({ path: join(root, 'company-profile.png'), fullPage: true });
  await admin.getByRole('button', { name: 'Salva anagrafica', exact: true }).click(); await expect(admin).toHaveURL(new RegExp(`/companies/${company.id}$`));
  expect((await db.company.findUniqueOrThrow({ where: { id: company.id } })).pec).toBeNull();
  await admin.getByRole('link', { name: 'Gestisci referenti', exact: true }).click();
  const adding = admin.locator('form').filter({ has: admin.locator('input[name="kind"][value="new-person"]') });
  await adding.locator('input[name="firstName"]').fill('Synthetic'); await adding.locator('input[name="lastName"]').fill('Contact');
  await adding.locator('input[name="role"]').fill('Referente'); await adding.locator('input[name="email"]').fill('contact@example.test');
  await adding.getByRole('button', { name: 'Aggiungi referente', exact: true }).click(); await expect(admin).toHaveURL(/#referenti$/);
  await expect(admin.getByText('Synthetic Contact', { exact: true })).toBeVisible();
  await admin.getByRole('link', { name: 'Gestisci referenti', exact: true }).click();
  const editing = admin.locator('form').filter({ has: admin.locator('input[name="kind"][value="person"]') });
  await editing.locator('input[name="role"]').fill('Amministratore');
  await editing.getByRole('button', { name: 'Salva referente', exact: true }).click(); await expect(admin).toHaveURL(/#referenti$/);
  await expect(admin.getByText('Amministratore', { exact: true })).toBeVisible();
  await login(outsider, 'outsider'); const denied = await outsider.goto(`/companies/${company.id}/edit`); expect(denied?.status()).toBe(404);
  await login(owner, 'owner'); await owner.goto(`/companies/${company.id}/edit`);
  await owner.locator('input[name="name"]').fill('Must not save');
  await db.userPermissionOverride.create({ data: { userId: f.ownerId, permission: 'company.write', allowed: false } });
  await owner.getByRole('button', { name: 'Salva anagrafica', exact: true }).click();
  await expect(owner.getByRole('alert')).toContainText('Salvataggio non autorizzato');
  expect((await db.company.findUniqueOrThrow({ where: { id: company.id } })).name).toBe('Profiles Browser Company');
  writeFileSync(join(root, 'browser-proof.json'), JSON.stringify({ synthetic: true, lead: true, client: true, company: true, nullClearing: true,
    zeroPreserved: true, personCreateAndEdit: true, outsiderDenied: true, revokedOpenFormDenied: true }));
  await ac.close(); await oc.close(); await xc.close();
});
